<?php
// YEAR(?03), WORD(?04_1), NUMBER(?04_2)
return array(
    // 登記
    "MOICAT.RALID" => "A",   // 土地標示部
    "MOICAT.RBLOW" => "B",   // 土地所有權部
    "MOICAT.RCLOR" => "C",   // 他項權利部
    "MOICAT.RDBID" => "D",   // 建物標示部
    "MOICAT.REBOW" => "E",   // 建物所有權部
    "MOICAT.RLNID" => "L",   // 人檔
    "MOICAT.RRLSQ" => "R",   // 權利標的
    "MOICAT.RGALL" => "G",   // 其他登記事項
    "MOICAT.RMNGR" => "M",   // 管理者
    "MOICAT.RTOGH" => "T",   // 他項權利檔
    "MOICAT.RHD10" => "H",   // 基地坐落／地上建物
    "MOICAT.RINDX" => "II",  // 案件索引, RINDX must be kept usually (unless you want to delete whole case)
    "MOICAT.RINXD" => "ID",
    "MOICAT.RINXR" => "IR",
    "MOICAT.RINXR_EN" => "IRE",
    "MOICAT.RJD14" => "J",
    "MOICAT.ROD31" => "O",
    "MOICAT.RPARK" => "P",
    "MOICAT.RPRCE" => "PB",
    "MOICAT.RSCNR" => "SR",
    "MOICAT.RSCNR_EN" => "SRE",
    "MOICAT.RVBLOW" => "VB",
    "MOICAT.RVCLOR" => "VC",
    "MOICAT.RVGALL" => "VG",
    "MOICAT.RVMNGR" => "VM",
    "MOICAT.RVPON" => "VP",  // 重測/重劃暫存
    "MOICAT.RVRLSQ" => "VR",
    "MOICAT.RXIDD04" => "ID",
    "MOICAT.RXLND" => "XL",
    "MOICAT.RXPRI" => "XP",
    "MOICAT.RXSEQ" => "XS",
    "MOICAT.B2104" => "BR",
    "MOICAT.B2118" => "BR",
    "MOICAT.BGALL" => "G",
    "MOICAT.BHD10" => "H",
    "MOICAT.BJD14" => "J",
    "MOICAT.BMNGR" => "M",
    "MOICAT.BOD31" => "O",
    "MOICAT.BPARK" => "P",
    "MOICAT.BRA26" => "C",
    "MOICAT.BRLSQ" => "R",
    "MOICAT.BXPRI" => "XP",
    "MOICAT.DGALL" => "G",
    // 地價
    "MOIPRT.PPRCE" => "MA",
    "MOIPRT.PGALL" => "GG",
    "MOIPRT.PBLOW" => "LA",
    "MOIPRT.PALID" => "KA",
    "MOIPRT.PNLPO" => "NA",
    "MOIPRT.PBLNV" => "BA",
    "MOIPRT.PCLPR" => "CA",
    "MOIPRT.PFOLP" => "FA",
    "MOIPRT.PGOBP" => "GA",
    "MOIPRT.PAPRC" => "AA",
    "MOIPRT.PEOPR" => "EA",
    "MOIPRT.POA11" => "OA",
    "MOIPRT.PGOBPN" => "GA",
    //"MOIPRC.PKCLS" => "KK",
    "MOIPRT.PPRCE" => "MA",
    "MOIPRT.P76SCRN" => "SS",
    "MOIPRT.P21T01" => "TA",
    "MOIPRT.P76ALID" => "AS",
    "MOIPRT.P76BLOW" => "BS",
    "MOIPRT.P76CRED" => "BS",
    "MOIPRT.P76INDX" => "II",
    "MOIPRT.P76PRCE" => "UP",
    "MOIPRT.P76SCRN" => "SS",
    "MOIPRT.PAE0301" => "MA",
    "MOIPRT.PB010" => "TP",
    "MOIPRT.PB014" => "TB",
    "MOIPRT.PB015" => "TB",
    "MOIPRT.PB016" => "TB",
    "MOIPRT.PHIND" => "II", // 案件索引, PHIND must be kept usually (unless you want to delete whole case)
    "MOIPRT.PNLPO" => "NA",
    "MOIPRT.POA11" => "OA"
);
