<?php
// 登記處理註記
return "(CASE
    WHEN RM02 = 'HA81' THEN '桃資登'
    WHEN RM02 = 'HA82' THEN '桃資總'
    WHEN RM02 = 'HA85' THEN '桃資更'
    WHEN RM02 = 'HA87' THEN '桃資速'
    WHEN RM02 = 'HAB1' THEN '壢桃登跨'
    WHEN RM02 = 'HAC1' THEN '溪桃登跨'
    WHEN RM02 = 'HAD1' THEN '楊桃登跨'
    WHEN RM02 = 'HAE1' THEN '蘆桃登跨'
    WHEN RM02 = 'HAF1' THEN '德桃登跨'
    WHEN RM02 = 'HAG1' THEN '平桃登跨'
    WHEN RM02 = 'HAH1' THEN '山桃登跨'
    WHEN RM02 = 'HBA1' THEN '桃壢登跨'
    WHEN RM02 = 'HCA1' THEN '桃溪登跨'
    WHEN RM02 = 'HDA1' THEN '桃楊登跨'
    WHEN RM02 = 'HEA1' THEN '桃蘆登跨'
    WHEN RM02 = 'HFA1' THEN '桃德登跨'
    WHEN RM02 = 'HGA1' THEN '桃平登跨'
    WHEN RM02 = 'HHA1' THEN '桃山登跨'
    WHEN RM02 = 'HB04' THEN '壢登'
    WHEN RM02 = 'HB05' THEN '壢永'
    WHEN RM02 = 'HB06' THEN '壢速'
    WHEN RM02 = 'HFB1' THEN '壢德登跨'
    WHEN RM02 = 'HCB1' THEN '壢溪登跨'
    WHEN RM02 = 'HGB1' THEN '壢平登跨'
    WHEN RM02 = 'HDB1' THEN '壢楊登跨'
    WHEN RM02 = 'HBG1' THEN '平壢登跨'
    WHEN RM02 = 'HBE1' THEN '蘆壢登跨'
    WHEN RM02 = 'HBH1' THEN '山壢登跨'
    WHEN RM02 = 'HEB1' THEN '蘆壢登跨'
    WHEN RM02 = 'HBF1' THEN '德壢登跨'
    WHEN RM02 = 'HHB1' THEN '壢山登跨'
    WHEN RM02 = 'HBD1' THEN '楊壢登跨'
    WHEN RM02 = 'HBC1' THEN '溪壢登跨'
    ELSE RM02
END)";
