SELECT GG00 || ',' ||
       GG48 || ',' ||
       B.KCNT || ',' ||
       GG49 || ',' ||
       GG01 || ',' ||
       GG02 || ',' ||
       GG30_1 || ',' ||
       C.KCNT || ',' ||
       GG30_2 || ',' ||
       CASE WHEN GG_FLAG = 'Y' THEN '查封註記' ELSE GG_FLAG END AS AI02901_B
  FROM SRGALL A, SRKEYN B, SRKEYN C
 WHERE
--A.GG48 in ('0362', '0363') -- A20
-- A.GG48 in ('0200', '0202', '0205', '0210') -- A21
-- A.GG48 in ('0255') -- 草漯
-- A.GG48 in ('0255', '0275', '0277', '0278', '0377') -- 草漯UNIT3
-- A.GG48 in ('0255', '0377', '0392') -- 草漯UNIT6
--(A.GG48 || A.GG49 between '031800000000' and '032299999999') -- 中壢運動公園
--A.GG48 in ('0213', '0222')  -- 中原
   AND (B.KCDE_1 = '48')
   AND (A.GG48 = B.KCDE_2)
   AND (C.KCDE_1 = '30')
   AND (A.GG30_1 = C.KCDE_2)
   AND (A.GG30_1 IN ('HO',
                     'GM',
                     'GL',
                     'GK',
                     'GJ',
                     'GH',
                     'GG',
                     'GF',
                     'GA',
                     'G7',
                     'G6',
                     'G5',
                     'G4',
                     'G3',
                     'G2',
                     'G1',
                     'E9',
                     'E8',
                     'E7',
                     'DC',
                     'DB',
                     'DA',
                     'D9',
                     'D5',
                     'D4',
                     'D1',
                     'C7',
                     'C4',
                     'C3',
                     'C2',
                     'C1',
                     'AS',
                     'AR',
                     'AQ',
                     'AP',
                     'AO',
                     'AN',
                     'AM',
                     'AL',
                     'AK',
                     'AJ',
                     'AH',
                     'AG',
                     'AF',
                     'AE',
                     'AD',
                     'AC',
                     'AB',
                     'AA',
                     'A7',
                     'A6',
                     'A5',
                     'A4',
                     'A1',
                     '9K',
                     '9I',
                     '9H',
                     '9G',
                     '9F',
                     '9E',
                     '9D',
                     '9B',
                     '9A',
                     '99',
                     '88',
                     '26',
                     '25',
                     '24',
                     '20',
                     '19',
                     '18',
                     '17',
                     '16',
                     '15',
                     '13',
                     '12',
                     '11',
                     '10',
                     '09',
                     '00',
                     '-',
                     'GZ',
                     'DD',
                     'GY',
                     'GX',
                     'GW',
                     'GV',
                     'GU',
                     'GT',
                     'GS',
                     'GR',
                     'GQ',
                     'AT',
                     '9L',
                     'GP',
                     'GN',
                     'GO',
                     'A8',
                     '9O',
                     'HB',
                     'HA',
                     'H9',
                     'H8',
                     'H7',
                     'H6',
                     'H5',
                     'H4',
                     'H3',
                     '9N',
                     'H2',
                     'AV',
                     '66',
                     '9M',
                     'HI',
                     'HH',
                     'HG',
                     'HF',
                     'HE',
                     'HD',
                     'DE',
                     'HC',
                     'HN',
                     'HM',
                     'HL',
                     'HK',
                     'HJ',
                     'AX',
                     'AW',
                     '9P',
                     'H1'))
   AND (A.GG00 IN ('A', 'B', 'C'))